imports:
    - { resource: @NSCoreBundle/Resources/config/app/sylius.yml }
    - { resource: @NSCoreBundle/Resources/config/app/ns.yml }

twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'

doctrine_cache:
    providers:
        sylius_rbac: %sylius.cache%

stof_doctrine_extensions:
    default_locale: %locale%
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            loggable: true
            sortable: true

fos_rest:
    view:
        formats:
            json: true
            xml:  true
        empty_content: 204

hwi_oauth:
    firewall_name: main
    resource_owners:
        amazon:
            type:          amazon
            client_id:     %ns.oauth.amazon.clientid%
            client_secret: %ns.oauth.amazon.clientsecret%
        facebook:
            type:          facebook
            client_id:     %ns.oauth.facebook.clientid%
            client_secret: %ns.oauth.facebook.clientsecret%
            scope:         "email"
            infos_url:     "https://graph.facebook.com/me?fields=id,name,email"
            options:
                display: popup
        google:
            type:          google
            client_id:     %ns.oauth.google.clientid%
            client_secret: %ns.oauth.google.clientsecret%
            scope:         "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
            options:
                access_type:     online
                approval_prompt: force
                display:         popup
                login_hint:      email address
